version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      npm:
        patterns:
          - "*"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      gha:
        patterns:
          - "*"
    versioning-strategy: increase
