name: v3-cd
on:
  push:
    branches:
      - v3

jobs:
  npm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Get Node version from Node manifest
        run: |
          echo "NODE_VER=$(jq -r '.engines.node' package.json | sed 's/v//' )" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: npm ci
      - name: Prepare for test
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v2.2.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: stable
