name: v3
on:
  push:
    branches:
      - v3

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
      - name: Get Node version from Node manifest
        run: echo "NODE_VER=$(curl -s https://nwjs.io/versions | jq -r ".versions[0].components.node")" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: stable
