name: ci
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  # test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #       node: [14, 16, 18]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2.2.1
  #       with:
  #         version: 7.1.0
  #         run_install: true

  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}

  #     - run: pnpm install
  #     - run: pnpm format
  #     - run: pnpm lint
  #     - run: pnpm test
  build:
    strategy:
      matrix:
        os: [windows-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.0
          run_install: true

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm install
      - run: pnpm demo