name: ci
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
          npm-version: '8.5.0'
      - run: npm ci
      - run: npm run format
      - run: npm run lint
      - run: npm run test
