name: v3-ci
on:
  pull_request:
    branches:
      - v3
  workflow_dispatch:
    branches:
      - v3

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    strategy:
      matrix:
        os: [macos-13, ubuntu-22.04, windows-2022]
        node: [16, 18, 20]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: {{ matrix.node }}
          cache: "npm"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: npm ci
      - name: Prepare test environment
        run: npm run test:prep
      - name: Run Jest tests
        run: npm run test:jest
      - name: Run Tape tests
        run: npm run test:tape
      - name: Run ChromeDriver tests
        run: npm run test:sanity
