name: ci
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
        node-version: ["19.3.0"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # - uses: actions/setup-node@v3.6.0
      #   with:
      #     node-version: "19.3.0"
      - uses: actions/checkout@v3.3.0
      - run: npm ci
      - run: npm run fmt
      - run: npm run lnt
      - run: npm run e2e
