name: doc

on:
  push:
    branches: ["*"]

jobs:
  doc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: "20.2.0"
    - run: npm ci
    - run: npm run doc:api
    - run: npm run doc:bld
    - name:
      uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
