name: doc

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

defaults:
  run:
    working-directory: [ "doc", "src" ]

jobs:
  doc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: "20.2.0"
    - run: npm run doc:api
    - run: npm run doc:bld
    - run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d docs/.vitepress/dist -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
