name: e2e

on:
  pull_request:
    branches: [main]

jobs:
  e2e:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
        shell: [bash, bash, powershell]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "20.5.0"
          cache: "npm"
      - run: corepack enable
      - run: npm ci
      - run: npm run ci:fmt
      - run: npm run ci:lnt
      - run: npm link nw-builder
      - run: npm run test:unit
      - run: npm run test:e2e
