name: e2e

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    strategy:
      matrix:
        os: [macos-12]
        node: [21]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install packages
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: gpatch
          choco: patch
          apt: patch
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: npm ci
      - name: Check for linting errors
        run: npm run lint
      - name: Link module
        run: npm link nw-builder
      - name: Run Selenium tests
        run: npm run test:e2e
