name: cd

on:
  push:
    branches: [main]

jobs:
  npm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 21

      - run: npm ci
      - uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
