name: release-please
on:
  push:
    branches:
      - v3

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: v3
