on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v4.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          changelog-sections: >
            [{"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"feat","section":"Features","hidden":false},
            {"type":"chore","section":"Chores","hidden":false},
