name: ci
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        node-version: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
          npm-version: '8.5.0'
      - run: npm ci
      - run: npm run demo
